
//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     Mudanças neste arquivo podem causar comportamento incorreto e serão perdidas
//     quando o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------
module Api.Marca.Listar {
    export interface Dto {
        id: number;
        descricao?: string;
    }

    export interface Query {
    }
}

export default Api
